CDAP-15550 Netezza db plugin enhacements: all data types support + pr…
vladhlinskiy/database-plugins pull request #10
Opened 2019-07-03 16:41 UTC by vladhlinskiy

…oper test coverage

2019-07-05 18:40 UTC, mlozbin-cybervisiontech requested changes

2019-07-05 18:40 UTC, mlozbin-cybervisiontech commented on netezza-plugin/src/test/java/io/cdap/plugin/netezza/NetezzaPluginTestBase.java
> +      stmt.execute("create table MY_TABLE (INTEGER_COL INTEGER, BYTEINT_COL BYTEINT, SMALLINT_COL SMALLINT, " +
what is the reason to reformat this part? Now it is not readable

2019-07-05 18:40 UTC, mlozbin-cybervisiontech commented on netezza-plugin/src/test/java/io/cdap/plugin/netezza/NetezzaPluginTestBase.java
> +      DATAPIPELINE_ARTIFACT_ID,
Do you use CDAP codestyle settings? Format looks strange.

2019-07-05 18:40 UTC, mlozbin-cybervisiontech commented on netezza-plugin/src/test/java/io/cdap/plugin/netezza/NetezzaPluginTestBase.java
> +    try (Statement stmt = conn.createStatement()) {
please try to avoid non-related refactoring

2019-07-06 08:24 UTC, vladhlinskiy commented
@mlozbin-cybervisiontech all style issues were addressed.

2019-07-08 12:20 UTC, mlozbin-cybervisiontech approved these changes

2019-07-09 14:52 UTC, merged